name: Linter
run-name: ${{ github.actor }} runs static lint 🚀
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftLint with --strict flag
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
