name: CI
run-name: ${{ github.actor }} runs main pipeline 🚀
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      scheme:
        description: 'The scheme to build'
        required: false
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-lint:
    uses: ./.github/workflows/reusable-lint.yml
  pr-test:
    uses: ./.github/workflows/reusable-tuist-test.yml
    with:
      scheme: ${{ inputs.scheme }}
