name: CI
run-name: ${{ github.actor }} runs main pipeline 🚀
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      scheme:
        description: 'The scheme to build'
        required: false
        type: string
jobs:
  build:
    uses: ./.github/workflows/reusable-tuist-build.yml
    with:
      scheme: ${{ github.event.inputs.scheme }}
