name: Export OpenTelemetry Trace for CI

on:
  workflow_run:
    workflows:
      - CI
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
        - name: Status
          run: |
            echo "The workflow run has completed."
            echo ${{ github.event.workflow.path }}

    #   - name: Export Workflow Trace
    #     uses: corentinmusard/otel-cicd-action@v1
    #     with:
    #       otlpEndpoint: ${{ secrets.DASH0_OTLP_ENDPOINT }}
    #       otlpHeaders: ${{ secrets.DASH0_OTLP_HEADERS }}
    #       githubToken: ${{ secrets.GITHUB_TOKEN }}
    #       runId: ${{ github.event.workflow_run.id }}
