name: reusables/tuist-test
on:
  workflow_dispatch:
    inputs:
      scheme:
        description: 'The scheme to build'
        required: false
        type: string
  workflow_call:
    inputs:
      scheme:
        description: 'The scheme to build'
        required: false
        type: string
jobs:
  build:
    runs-on: macos-15
    env:
      TUIST_TEST_PLATFORM: iOS
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0 https://github.com/actions/checkout
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2 https://github.com/jdx/mise-action
        with:
          install: true
          install_args: "tuist"
          cache: true
          log_level: debug
      - name: Cleanup
        run: |
          tuist clean
      - name: Tuist Install
        run: |
          tuist install
      - name: Tuist Generate
        run: |
          # Running tuist generate to propagate only target destinations / platforms
          tuist generate --no-open
      - name: Test
        run: |
          tuist test ${{ inputs.scheme }}
